name: "K-Tree Clustering Software"
description: "K-Tree for Big Data"

layout: example

#url: "http://localhost:4000"
#url: "http://big-data-lab.github.io/K-Tree/"
baseurl: "/K-Tree"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments
